name: Build Mac (Experimental)

on:
  push:
    branches:
      - main

jobs:
  mac:
    name: Bundle to macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-15-intel]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Homebrew dependencies
        run: |
          brew install gtk4 adwaita-icon-theme libadwaita python cairo cmake dbus glib gstreamer

      - name: Install Python dependencies
        run: |
          pip install meson-python ninja
          pip install --no-build-isolation --break-system-packages -r requirements-mac.txt
          pip install --no-build-isolation --break-system-packages pyinstaller

      - name: Bundle application
        run: |
          zsh mac/bundle.sh
          zip -r Mixtapes.zip dist/Mixtapes.app

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: Mixtapes.zip
          path: Mixtapes.zip
