name: Build Mac (Experimental)

on:
  push:
    branches:
      - main


jobs:
  macos:
    strategy:
      matrix:
        include:
          - os: macos-14
            arch: arm64
          - os: macos-15-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Compile GResources
        run: |
          brew install glib
          glib-compile-resources --sourcedir=. src/muse.gresource.xml --target=src/muse.gresource
      - name: Build Mixtapes
        run: bash mac/mixtapes-macos-helper.sh
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Upload dmg
        uses: actions/upload-artifact@v4
        with:
          name: mixtapes-mac-${{ matrix.arch }}
          path: mixtapes-*.dmg
